### ISSUE TITLE
message still serialized between nodelets

### ISSUE THREAD

**Issue by protobits** [ros/nodelet_core#16] opened 2014-04-14 15:34 UTC
I'm currently trying to pass a C++ object between nodelets, for which I have provided the necessary traits (MD5, etc.), in order for it to be accepted by ROS as a message. 
Since my goal is to pass a specific object (a static map) between nodelets efficiently, I would like to avoid serializing this message.
Furthermore, since this is an internal message between my nodelet framework for the package I'm developing, this object is never going to sent to a standard node. In this sense, when I defined the traits, I also defined the allInOne serialization function without any actual functionality. However, I'm throwing an exception and printing a message in order to check that the serialization function is never called, as it should be when using nodelets. However, this is not the case and the exception is being thrown.

I'm currently publishing as per ROS guidelines (publishing a boost::shared_ptr), so I'm wondering why is this message still being serialized. I've looked into the code of ros::Publisher::publish() for this case (with shared_ptr) and I really don't understand why the serializeMessage call is being made. Shouldn't this be avoided with a nodelet?

**Comment by protobits** [comment] 2014-04-14 16:38
I think I've found the problem. I was publishing from within the "new subscriber" callback:

```
void surfnav::MapManager::new_subscriber(const ros::SingleSubscriberPublisher& pub)
{
  pub.publish(map);
}
```

This triggers the serialization for some reason. If publising on the regular publisher, it works as expected.

I still don't understand how all of this is achieved. There's some black magic going in the nodelet code.

**Comment by dirk-thomas** [comment] 2014-04-14 17:11
This is likely not a bug but just a wrong usage (since it is likely that it would have been noticed by now if nodelets would always serialize). Please post more information about your usage, e.g. some source code might help. Also consider asking questions like this on answers.ros.org first..

**Comment by protobits** [comment] 2014-04-15 15:35
When I'm publishing using a shared_ptr on the publisher directly, if I print the pointer value before being sent and the when it is received, I get the same value and the serializer function is not called. In other words, no serialization nor copies occur.
However, when I publish from the callback previously shown, which is triggered by:

```
map_pub = nh.advertise<surfnav::Map>("/surfnav/map", 1, boost::bind(&MapManager::new_subscriber, this, _1));
```

If I print the pointer as:

```
ROS_INFO_STREAM("sent map (on connect): " << (uint64_t)map.get());
```

before calling pub.publish(), the value differs from the receiver side (which is the same in both cases). Also, the serialization function is called (I'm printing a message from its body and I can see it). This makes me feel that when using this form of publishing, serialization is invoked for some reason.

**Comment by dirk-thomas** [comment] 2014-04-15 17:34
Zero copy only happens when publishing a _shared_ptr_. Publishing a reference will always perform serialization since there is no way to pass ownership of the data.

**Comment by protobits** [comment] 2014-04-15 17:35
As I mentioned before, I am publishing a shared_ptr, not a reference.

**Comment by dirk-thomas** [comment] 2014-04-15 17:48
Please provide more code - at best a simple (self containing) code example which can be compiled and run.

**Comment by dirk-thomas** [comment] 2014-04-15 17:52
The `SingleSubscriberPublisher` might not support zero-copy either. It looks like that it is always serializing: https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/single_subscriber_publisher.h

**Comment by protobits** [comment] 2014-04-15 17:56
Ok, that must be it. I was suspecting the same thing.
I can't provide self-contained compilable code right now as it is not
simple for me. If needed, I can try to provide it but it will take some
time. However, I see you already have the responsible code in view. Maybe
this is something that I should submit to roscpp.

**Comment by dirk-thomas** [comment] 2014-04-15 18:22
You might fill a ticket for changing the `SingleSubscriberPublisher` to `roscpp` but without a pull request the chances are pretty low that it will be addressed in the near future.

You might just want to use a "normal" publisher to avoid serialization or does that not work for you?

**Comment by protobits** [comment] 2014-04-15 18:34
Ok, I will create a ticket there.
Actually, I wanted this type of publishing to somehow workaround the lack
of zero-copy services. Instead of having a service that provides a map, I
was just sending the map when someone subscribed. At the moment I changed
it so that a service triggers a normal publish. In this way, I almost have
the functionality I need.

**Comment by dirk-thomas** [comment] 2014-04-21 17:33
I will close this ticket since `nodelet_core` is not the reason here. If you think `SingleSubscriberPublisher` should be patched please fill a ticket for it as mentioned before.

**Closed as completed by dirk-thomas** 2014-04-21 17:33 UTC
Labels: invalid
